Implementing MySQL interface

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -889,6 +889,12 @@ POSTGRESQL_LDFLAGS
 HAVE_POSTGRESQL
 COMPILE_POSTGRESQL_STUFF_TRUE
 COMPILE_POSTGRESQL_STUFF_FALSE
+MYSQL_CONFIG
+MYSQL_CPPFLAGS
+MYSQL_LDFLAGS
+HAVE_MYSQL
+COMPILE_MYSQL_STUFF_TRUE
+COMPILE_MYSQL_STUFF_FALSE
 PKG_CONFIG
 VALGRIND
 XSLTPROC
@@ -1543,6 +1549,7 @@ Optional Packages:
                           use PostgreSQL API headers from given path
   --with-postgresql-lib=[DIR]
                           use PostgreSQL API libraries from given path
+  --with-mysql            use MySQL API
   --enable-debug          enable debug code (assert statements)
   --enable-crash          enable crash simulation code
   --disable-trace         disable trace feature (not suggested)
@@ -4375,7 +4382,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4378 "configure"' > conftest.$ac_ext
+  echo '#line 4385 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7432,11 +7439,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7435: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7442: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7439: \$? = $ac_status" >&5
+   echo "$as_me:7446: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7722,11 +7729,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7725: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7732: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7729: \$? = $ac_status" >&5
+   echo "$as_me:7736: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7826,11 +7833,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7829: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7836: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7833: \$? = $ac_status" >&5
+   echo "$as_me:7840: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10203,7 +10210,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10206 "configure"
+#line 10213 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10303,7 +10310,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10306 "configure"
+#line 10313 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12704,11 +12711,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12707: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12714: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12711: \$? = $ac_status" >&5
+   echo "$as_me:12718: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12808,11 +12815,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12811: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12818: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12815: \$? = $ac_status" >&5
+   echo "$as_me:12822: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14406,11 +14413,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14409: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14416: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14413: \$? = $ac_status" >&5
+   echo "$as_me:14420: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14510,11 +14517,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14513: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14520: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14517: \$? = $ac_status" >&5
+   echo "$as_me:14524: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16730,11 +16737,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16733: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16740: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16737: \$? = $ac_status" >&5
+   echo "$as_me:16744: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17020,11 +17027,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17023: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17030: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17027: \$? = $ac_status" >&5
+   echo "$as_me:17034: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17124,11 +17131,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17127: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17134: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17131: \$? = $ac_status" >&5
+   echo "$as_me:17138: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20602,7 +20609,7 @@ fi
 
 ac_config_headers="$ac_config_headers config.h"
 
-ac_config_files="$ac_config_files Makefile doc/Makefile doc/examples/Makefile doc/manuals/Makefile etc/lixac_conf.xml etc/lixad_conf.xml etc/Makefile src/Makefile src/common/Makefile src/common/lixa_inst_conf.c src/client/Makefile src/client/switch/Makefile src/client/switch/lixa/Makefile src/client/switch/ibmdb2/Makefile src/client/switch/oracle/Makefile src/client/switch/postgresql/Makefile src/server/Makefile src/sample/Makefile tests/Makefile tests/atlocal tests/etc/lixac_conf.xml tests/etc/lixad_conf.xml tests/etc/Makefile tests/src/Makefile var/Makefile doxygen.conf"
+ac_config_files="$ac_config_files Makefile doc/Makefile doc/examples/Makefile doc/manuals/Makefile etc/lixac_conf.xml etc/lixad_conf.xml etc/Makefile src/Makefile src/common/Makefile src/common/lixa_inst_conf.c src/client/Makefile src/client/switch/Makefile src/client/switch/lixa/Makefile src/client/switch/ibmdb2/Makefile src/client/switch/oracle/Makefile src/client/switch/postgresql/Makefile src/client/switch/mysql/Makefile src/server/Makefile src/sample/Makefile tests/Makefile tests/atlocal tests/etc/lixac_conf.xml tests/etc/lixad_conf.xml tests/etc/Makefile tests/src/Makefile var/Makefile doxygen.conf"
 
 ac_config_commands="$ac_config_commands tests/atconfig"
 
@@ -21428,6 +21435,89 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 else
   COMPILE_POSTGRESQL_STUFF_TRUE='#'
   COMPILE_POSTGRESQL_STUFF_FALSE=
+fi
+
+# Include MySQL test
+
+
+
+
+    HAVE_MYSQL="no"
+
+# Check whether --with-mysql was given.
+if test "${with_mysql+set}" = set; then
+  withval=$with_mysql; HAVE_MYSQL="maybe"
+else
+  HAVE_MYSQL="no"
+
+fi
+
+    if test "$HAVE_MYSQL" != "no"
+    then
+        for ac_prog in mysql_config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_MYSQL_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MYSQL_CONFIG"; then
+  ac_cv_prog_MYSQL_CONFIG="$MYSQL_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_MYSQL_CONFIG="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+MYSQL_CONFIG=$ac_cv_prog_MYSQL_CONFIG
+if test -n "$MYSQL_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $MYSQL_CONFIG" >&5
+echo "${ECHO_T}$MYSQL_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$MYSQL_CONFIG" && break
+done
+
+        if test -z $MYSQL_CONFIG
+        then
+            { { echo "$as_me:$LINENO: error: cannot find mysql_config program" >&5
+echo "$as_me: error: cannot find mysql_config program" >&2;}
+   { (exit 1); exit 1; }; }
+        else
+            MYSQL_CPPFLAGS=$($MYSQL_CONFIG --include)
+            MYSQL_LDFLAGS=$($MYSQL_CONFIG --libs_r)
+            HAVE_MYSQL="yes"
+        fi
+    fi
+
+
+
+
+
+ if test "$HAVE_MYSQL" = "yes"; then
+  COMPILE_MYSQL_STUFF_TRUE=
+  COMPILE_MYSQL_STUFF_FALSE='#'
+else
+  COMPILE_MYSQL_STUFF_TRUE='#'
+  COMPILE_MYSQL_STUFF_FALSE=
 fi
 
 
@@ -30270,6 +30360,13 @@ echo "$as_me: error: conditional \"COMPILE_POSTGRESQL_STUFF\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COMPILE_MYSQL_STUFF_TRUE}" && test -z "${COMPILE_MYSQL_STUFF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COMPILE_MYSQL_STUFF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COMPILE_MYSQL_STUFF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_XSLTPROC_TRUE}" && test -z "${HAVE_XSLTPROC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_XSLTPROC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -30762,6 +30859,7 @@ do
     "src/client/switch/ibmdb2/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/ibmdb2/Makefile" ;;
     "src/client/switch/oracle/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/oracle/Makefile" ;;
     "src/client/switch/postgresql/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/postgresql/Makefile" ;;
+    "src/client/switch/mysql/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/mysql/Makefile" ;;
     "src/server/Makefile") CONFIG_FILES="$CONFIG_FILES src/server/Makefile" ;;
     "src/sample/Makefile") CONFIG_FILES="$CONFIG_FILES src/sample/Makefile" ;;
     "tests/Makefile") CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
@@ -30997,6 +31095,12 @@ POSTGRESQL_LDFLAGS!$POSTGRESQL_LDFLAGS$ac_delim
 HAVE_POSTGRESQL!$HAVE_POSTGRESQL$ac_delim
 COMPILE_POSTGRESQL_STUFF_TRUE!$COMPILE_POSTGRESQL_STUFF_TRUE$ac_delim
 COMPILE_POSTGRESQL_STUFF_FALSE!$COMPILE_POSTGRESQL_STUFF_FALSE$ac_delim
+MYSQL_CONFIG!$MYSQL_CONFIG$ac_delim
+MYSQL_CPPFLAGS!$MYSQL_CPPFLAGS$ac_delim
+MYSQL_LDFLAGS!$MYSQL_LDFLAGS$ac_delim
+HAVE_MYSQL!$HAVE_MYSQL$ac_delim
+COMPILE_MYSQL_STUFF_TRUE!$COMPILE_MYSQL_STUFF_TRUE$ac_delim
+COMPILE_MYSQL_STUFF_FALSE!$COMPILE_MYSQL_STUFF_FALSE$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 VALGRIND!$VALGRIND$ac_delim
 XSLTPROC!$XSLTPROC$ac_delim
@@ -31022,7 +31126,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 47; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
