Intermediate commit; it does not compile!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -881,6 +881,10 @@ IBMDB2_CLI_CPPFLAGS
 IBMDB2_CLI_LDFLAGS
 COMPILE_IBMDB2_STUFF_TRUE
 COMPILE_IBMDB2_STUFF_FALSE
+POSTGRESQL_CPPFLAGS
+POSTGRESQL_LDFLAGS
+COMPILE_POSTGRESQL_STUFF_TRUE
+COMPILE_POSTGRESQL_STUFF_FALSE
 PKG_CONFIG
 VALGRIND
 XSLTPROC
@@ -1530,6 +1534,11 @@ Optional Packages:
   --with-ibmdb2-include=[DIR]
                           use IBM DB2 CLI API headers from given path
   --with-ibmdb2-lib=[DIR] use IBM DB2 CLI API libraries from given path
+  --with-postgresql=[DIR] use PostgreSQL API from given path
+  --with-postgresql-include=[DIR]
+                          use PostgreSQL API headers from given path
+  --with-postgresql-lib=[DIR]
+                          use PostgreSQL API libraries from given path
   --enable-debug          enable debug code (assert statements)
   --enable-crash          enable crash simulation code
   --disable-trace         disable trace feature (not suggested)
@@ -4362,7 +4371,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4365 "configure"' > conftest.$ac_ext
+  echo '#line 4374 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7419,11 +7428,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7422: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7431: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7426: \$? = $ac_status" >&5
+   echo "$as_me:7435: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7709,11 +7718,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7712: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7721: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7716: \$? = $ac_status" >&5
+   echo "$as_me:7725: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7813,11 +7822,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7816: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7825: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7820: \$? = $ac_status" >&5
+   echo "$as_me:7829: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10190,7 +10199,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10193 "configure"
+#line 10202 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10290,7 +10299,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10293 "configure"
+#line 10302 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12691,11 +12700,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12694: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12703: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12698: \$? = $ac_status" >&5
+   echo "$as_me:12707: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12795,11 +12804,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12798: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12807: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12802: \$? = $ac_status" >&5
+   echo "$as_me:12811: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14393,11 +14402,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14396: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14400: \$? = $ac_status" >&5
+   echo "$as_me:14409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14497,11 +14506,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14500: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14509: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14504: \$? = $ac_status" >&5
+   echo "$as_me:14513: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16717,11 +16726,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16720: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16729: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16724: \$? = $ac_status" >&5
+   echo "$as_me:16733: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17007,11 +17016,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17010: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17014: \$? = $ac_status" >&5
+   echo "$as_me:17023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17111,11 +17120,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17114: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17123: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17118: \$? = $ac_status" >&5
+   echo "$as_me:17127: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20589,7 +20598,7 @@ fi
 
 ac_config_headers="$ac_config_headers config.h"
 
-ac_config_files="$ac_config_files Makefile doc/Makefile doc/examples/Makefile doc/manuals/Makefile etc/lixac_conf.xml etc/lixad_conf.xml etc/Makefile src/Makefile src/common/Makefile src/common/lixa_inst_conf.c src/client/Makefile src/client/switch/Makefile src/client/switch/lixa/Makefile src/client/switch/ibmdb2/Makefile src/client/switch/oracle/Makefile src/server/Makefile src/sample/Makefile tests/Makefile tests/atlocal tests/etc/lixac_conf.xml tests/etc/lixad_conf.xml tests/etc/Makefile tests/src/Makefile var/Makefile doxygen.conf"
+ac_config_files="$ac_config_files Makefile doc/Makefile doc/examples/Makefile doc/manuals/Makefile etc/lixac_conf.xml etc/lixad_conf.xml etc/Makefile src/Makefile src/common/Makefile src/common/lixa_inst_conf.c src/client/Makefile src/client/switch/Makefile src/client/switch/lixa/Makefile src/client/switch/ibmdb2/Makefile src/client/switch/oracle/Makefile src/client/switch/postgresql/Makefile src/server/Makefile src/sample/Makefile tests/Makefile tests/atlocal tests/etc/lixac_conf.xml tests/etc/lixad_conf.xml tests/etc/Makefile tests/src/Makefile var/Makefile doxygen.conf"
 
 ac_config_commands="$ac_config_commands tests/atconfig"
 
@@ -20891,6 +20900,7 @@ else
   COMPILE_ORACLE_STUFF_FALSE=
 fi
 
+# Include IBM DB2 test
 
 
 
@@ -21145,6 +21155,262 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 else
   COMPILE_IBMDB2_STUFF_TRUE='#'
   COMPILE_IBMDB2_STUFF_FALSE=
+fi
+
+# Include PostgreSQL test
+
+
+
+
+
+# Check whether --with-postgresql was given.
+if test "${with_postgresql+set}" = set; then
+  withval=$with_postgresql; postgresql_home_dir="$withval";postgresql_stuff="yes"
+else
+  postgresql_home_dir=""
+
+fi
+
+
+
+# Check whether --with-postgresql-include was given.
+if test "${with_postgresql_include+set}" = set; then
+  withval=$with_postgresql_include; postgresql_home_include_dir="$withval";postgresql_stuff="yes"
+else
+  postgresql_home_include_dir=""
+
+fi
+
+
+# Check whether --with-postgresql-lib was given.
+if test "${with_postgresql_lib+set}" = set; then
+  withval=$with_postgresql_lib; postgresql_home_lib_dir="$withval";postgresql_stuff="yes"
+else
+  postgresql_home_lib_dir=""
+
+fi
+
+
+    POSTGRESQL_CPPFLAGS=""
+    POSTGRESQL_LDFLAGS=""
+
+                case $host in
+      i?86-*-*-*)
+        POSTGRESQL_LIB_NAME="lib32"
+	;;
+      x86_64-*-*-*)
+        POSTGRESQL_LIB_NAME="lib64"
+	;;
+      *) { { echo "$as_me:$LINENO: error: LIXA is not yet ported on this architecture for PostgreSQL" >&5
+echo "$as_me: error: LIXA is not yet ported on this architecture for PostgreSQL" >&2;}
+   { (exit 1); exit 1; }; }
+        ;;
+    esac
+
+                want_postgresql_but_no_path="no"
+
+    if test -n "$postgresql_home_dir"; then
+
+        if test "$postgresql_home_dir" != "no" -a "$postgresql_home_dir" != "yes"; then
+                        postgresql_include_dir="$postgresql_home_dir/include"
+            postgresql_lib_dir="$postgresql_home_dir/$POSTGRESQL_LIB_NAME"
+        elif test "$postgresql_home_dir" = "yes"; then
+            want_postgresql_but_no_path="yes"
+        fi
+
+    elif test -n "$postgresql_home_include_dir" -o -n "$postgresql_home_lib_dir"; then
+
+        if test "$postgresql_home_include_dir" != "no" -a "$postgresql_home_include_dir" != "yes"; then
+            postgresql_include_dir="$postgresql_home_include_dir"
+        elif test "$postgresql_home_include_dir" = "yes"; then
+            want_postgresql_but_no_path="yes"
+        fi
+
+        if test "$postgresql_home_lib_dir" != "no" -a "$postgresql_home_lib_dir" != "yes"; then
+            postgresql_lib_dir="$postgresql_home_lib_dir"
+        elif test "$postgresql_home_lib_dir" = "yes"; then
+            want_postgresql_but_no_path="yes"
+        fi
+    fi
+
+    if test "$want_postgresql_but_no_path" = "yes"; then
+        { echo "$as_me:$LINENO: WARNING: POSTGRESQL support is requested but no POSTGRESQL paths have been provided. \
+Please, locate POSTGRESQL directories using --with-postgresql or \
+--with-postgresql-include and --with-postgresql-lib options." >&5
+echo "$as_me: WARNING: POSTGRESQL support is requested but no POSTGRESQL paths have been provided. \
+Please, locate POSTGRESQL directories using --with-postgresql or \
+--with-postgresql-include and --with-postgresql-lib options." >&2;}
+    fi
+
+                if test -n "$postgresql_include_dir" -a -n "$postgresql_lib_dir"; then
+
+        saved_CPPFLAGS="$CPPFLAGS"
+        CPPFLAGS="$CPPFLAGS -I$postgresql_include_dir"
+
+        saved_LDFLAGS="$LDFLAGS"
+        pql_ldflags="-Wl,-rpath,$postgresql_lib_dir -L$postgresql_lib_dir -lpq"
+        LDFLAGS="$LDFLAGS $pql_ldflags"
+
+                                { echo "$as_me:$LINENO: checking for Postgresql headers in $postgresql_include_dir" >&5
+echo $ECHO_N "checking for Postgresql headers in $postgresql_include_dir... $ECHO_C" >&6; }
+
+        ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+        cat >conftest.$ac_ext <<_ACEOF
+
+            /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libpq-fe.h>
+int
+main ()
+{
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+            POSTGRESQL_CPPFLAGS="-I$postgresql_include_dir"
+            pql_header_found="yes"
+            { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+            pql_header_found="no"
+            { echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+        ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+                                if test "$pql_header_found" = "yes"; then
+
+            { echo "$as_me:$LINENO: checking for Postgresql libraries in $postgresql_lib_dir" >&5
+echo $ECHO_N "checking for Postgresql libraries in $postgresql_lib_dir... $ECHO_C" >&6; }
+
+            ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+            cat >conftest.$ac_ext <<_ACEOF
+
+                /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libpq-fe.h>
+int
+main ()
+{
+
+PGconn *conn;
+conn = PQconnectdb("");
+return 0;
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+                POSTGRESQL_LDFLAGS="$pql_ldflags"
+                pql_lib_found="yes"
+                { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+                pql_lib_found="no"
+                { echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+            ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+        fi
+
+        CPPFLAGS="$saved_CPPFLAGS"
+        LDFLAGS="$saved_LDFLAGS"
+    fi
+
+
+
+
+ if test -n "$postgresql_stuff"; then
+  COMPILE_POSTGRESQL_STUFF_TRUE=
+  COMPILE_POSTGRESQL_STUFF_FALSE='#'
+else
+  COMPILE_POSTGRESQL_STUFF_TRUE='#'
+  COMPILE_POSTGRESQL_STUFF_FALSE=
 fi
 
 
@@ -29980,6 +30246,13 @@ echo "$as_me: error: conditional \"COMPILE_IBMDB2_STUFF\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COMPILE_POSTGRESQL_STUFF_TRUE}" && test -z "${COMPILE_POSTGRESQL_STUFF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COMPILE_POSTGRESQL_STUFF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COMPILE_POSTGRESQL_STUFF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_XSLTPROC_TRUE}" && test -z "${HAVE_XSLTPROC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_XSLTPROC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -30471,6 +30744,7 @@ do
     "src/client/switch/lixa/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/lixa/Makefile" ;;
     "src/client/switch/ibmdb2/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/ibmdb2/Makefile" ;;
     "src/client/switch/oracle/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/oracle/Makefile" ;;
+    "src/client/switch/postgresql/Makefile") CONFIG_FILES="$CONFIG_FILES src/client/switch/postgresql/Makefile" ;;
     "src/server/Makefile") CONFIG_FILES="$CONFIG_FILES src/server/Makefile" ;;
     "src/sample/Makefile") CONFIG_FILES="$CONFIG_FILES src/sample/Makefile" ;;
     "tests/Makefile") CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
@@ -30698,6 +30972,10 @@ IBMDB2_CLI_CPPFLAGS!$IBMDB2_CLI_CPPFLAGS$ac_delim
 IBMDB2_CLI_LDFLAGS!$IBMDB2_CLI_LDFLAGS$ac_delim
 COMPILE_IBMDB2_STUFF_TRUE!$COMPILE_IBMDB2_STUFF_TRUE$ac_delim
 COMPILE_IBMDB2_STUFF_FALSE!$COMPILE_IBMDB2_STUFF_FALSE$ac_delim
+POSTGRESQL_CPPFLAGS!$POSTGRESQL_CPPFLAGS$ac_delim
+POSTGRESQL_LDFLAGS!$POSTGRESQL_LDFLAGS$ac_delim
+COMPILE_POSTGRESQL_STUFF_TRUE!$COMPILE_POSTGRESQL_STUFF_TRUE$ac_delim
+COMPILE_POSTGRESQL_STUFF_FALSE!$COMPILE_POSTGRESQL_STUFF_FALSE$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 VALGRIND!$VALGRIND$ac_delim
 XSLTPROC!$XSLTPROC$ac_delim
@@ -30723,7 +31001,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
